site_name: AZ_geek
theme: readthedocs
nav:
- Home: index.md
- Mkdocs manual: Manual_of_Mkdocs.md
- Handwriting blog: handwriting.md
- calculator: calculator.md
- Zhige design: zhigedesign.md
- Linux: LinuxNotes.md
- PBC : PBClearn.md
- Pygame : Pygame.md
- Misc: Misc.md
- LanguageLearning: LanguageLearning.md


extra_javascript:
  - js/calculator.js